
CREATE TABLE STUDENTTBL
(
   STUDENT_ID VARCHAR(8) NOT NULL,
   NAME VARCHAR(30),
   PRIMARY KEY(STUDENT_ID)
);

CREATE TABLE COURSETBL
(
   COURSE_ID VARCHAR(8) NOT NULL,
   NAME VARCHAR(30),
   PRIMARY KEY(COURSE_ID)    
);

CREATE TABLE ENROLLTBL
(
   STUDENT_ID VARCHAR(8) NOT NULL,
   COURSE_ID VARCHAR(8) NOT NULL,
   PRIMARY KEY(STUDENT_ID,COURSE_ID)   
);