/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stanley_memmap_MemMapProxy */

#ifndef _Included_com_stanley_memmap_MemMapProxy
#define _Included_com_stanley_memmap_MemMapProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stanley_memmap_MemMapProxy
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_stanley_memmap_MemMapProxy_init
  (JNIEnv *, jobject);

/*
 * Class:     com_stanley_memmap_MemMapProxy
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stanley_memmap_MemMapProxy_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
