/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyWindow */

#ifndef _Included_MyWindow
#define _Included_MyWindow
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef MyWindow_TOP_ALIGNMENT
#define MyWindow_TOP_ALIGNMENT 0.0f
#undef MyWindow_CENTER_ALIGNMENT
#define MyWindow_CENTER_ALIGNMENT 0.5f
#undef MyWindow_BOTTOM_ALIGNMENT
#define MyWindow_BOTTOM_ALIGNMENT 1.0f
#undef MyWindow_LEFT_ALIGNMENT
#define MyWindow_LEFT_ALIGNMENT 0.0f
#undef MyWindow_RIGHT_ALIGNMENT
#define MyWindow_RIGHT_ALIGNMENT 1.0f
#undef MyWindow_serialVersionUID
#define MyWindow_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: nameCounter */
#undef MyWindow_serialVersionUID
#define MyWindow_serialVersionUID -2284879212465893870LL
#undef MyWindow_TIMER_SECONDS
#define MyWindow_TIMER_SECONDS 100L
/*
 * Class:     MyWindow
 * Method:    paintOpenGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyWindow_paintOpenGL
  (JNIEnv *, jobject);

/*
 * Class:     MyWindow
 * Method:    initializeOpenGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyWindow_initializeOpenGL
  (JNIEnv *, jobject);

/*
 * Class:     MyWindow
 * Method:    cleanupOpenGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyWindow_cleanupOpenGL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
